version: '3'
services:
  api:
    container_name: lap2_api
    image: 'node:12.18.4'
    working_dir: /code
    ports:
      - 5000:5000
    environment:
      - PGUSER=freetyper
      - PGHOST=db
      - PGPASSWORD=SQL015NoSQL
      - PGDATABASE=database
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run dev"
  db:
    container_name: lap2_db
    image: 'postgres:11.1'
    expose:
      - '5432'
    volumes:
      - 'databasedata:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d/:ro'
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=freetyper
      - POSTGRES_PASSWORD=SQL015NoSQL
volumes:
  databasedata:
